config/routes.rb
Rails.application.routes.draw do


root :to => 'cds#top'
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}

resources :cds, only: [:top, :index, :index_genre, :show, :update]
resources :favorites, only: [:create, :destroy]
resources :comments, only: [:index, :edit, :create, :update, :destroy]
#resources :carts, only: [:index, :destroy]
#resources :orders, only: [:show, :create]
get '/users/carts/:id' => 'carts#show',as: "user_cart"
post '/users/carts/:id' => 'carts#create'
post  'orders/:id' => 'orders#create',as: "create_order"
get  'orders/:id' => 'orders#show',as: "user_order"
get 'users/historys' => 'histories#index',as: "create_history"
post 'histories' => 'histories#create',as: "history_create"
resources :users, only: [:index, :show, :edit, :create, :update, :destroy]
resources :cart_items, only: [:create, :destroy]
#get '/users/carts' => 'carts#index'

namespace :admins do
      get '/cds/top' => 'cds#top'
  post '/cds/top' => 'cds#create'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :cds, only: [:index, :show, :edit, :create, :update, :destroy]

  # delete '/users' => 'users#destroy'
  resources :artists, only: [:new, :create, :destroy]
  resources :genres, only: [:new, :create, :destroy]
  resources :labels, only: [:new, :create, :destroy]

end


  get 'index_genre' => 'cds#index_genre'


end

app/models/user.rb
class User < ApplicationRecord
		has_many :carts


acts_as_paranoid

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  attachment :profile_image

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
	layout 'admin'

	PER = 2

	def index
		@users  = User.paginate(page: params[:PER])
        @search = User.ransack(params[:q])
        @result = @search.result
	end


	def show
		@user = User.find(params[:id])
		@cds  = Cd.paginate(page: params[:PER])
        @search = Cd.ransack(params[:q])
        @result = @search.result

	end

	def history
	end

	def edit
       @user = User.find(params[:id])
	end

	def update
		user = User.find(params[:id])
	    user.update(user_params)
	    redirect_to admins_users_path
	end

	def destroy
		    user = User.find(params[:id])
			user.destroy
		    redirect_to admins_users_path
	end

	private

  def user_params
    params.require(:user).permit(:name_kanji, :name_kana, :email, :postal_code, :address, :phone_number, :profile_image)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def after_sign_up_path_for(resource)
    root_path
  end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name_kanji, :name_kana, :email, :postal_code, :address, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_up_path_for(resource)
    root_path
  end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

# before_action :authenticate_user!

  def index
  end

  def show
    @user = current_user

  end

  def edit
  end

  def create
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(current_user.id)
  end

  def history
  end


private

  def user_params
    params.require(:user).permit(:name_kanji, :name_kana, :email, :postal_code, :address, :phone_number, :profile_image)
  end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/users/_result.html.erb
<tbody>
	<% @result.first(1).each do %>
	<tr>
		<td>
			<%= user.id %>
		</td>
		<td>
			<%= user.name_kanji %>
		</td>
		<td>
			<%= user.email %>
		</td>
		<td><%= link_to "詳細", admins_user_path(user.id) %></td>
      <td><%= link_to "編集", edit_admins_user_path(user.id) %></td>
      <td><%= link_to "削除", admins_user_path(user.id), method: :delete, data: { confirm: '削除しますか?' } %></td>
	</tr>
	<% end %>
</tbody>

app/views/admins/users/_user.html.erb
<tbody>
	<% @users.first(1).each do %>
	<tr>
		<td>
			<%= user.id %>
		</td>
		<td>
			<%= user.name_kanji %>
		</td>
		<td>
			<%= user.email %>
		</td>
		<td><%= link_to "詳細", admins_user_path(user.id) %></td>
      <td><%= link_to "編集", edit_admins_user_path(user.id) %></td>
      <td><%= link_to "削除", admins_user_path(user.id), method: :delete, data: { confirm: '削除しますか?' } %></td>
	</tr>
	<% end %>
</tbody>

app/views/admins/users/edit.html.erb
<h1>ユーザー設定</h1>
    <%= form_for @user, url:admins_user_path do |f| %>

    <%= f.attachment_field :profile_image, class: "user_image" %>


	<p>名前</p>
	<%= f.text_field :name_kanji, class: "name_kanji" %>

	<p>メールアドレス</p>
	<%= f.text_field :email, class: "email" %>

	<p>郵便番号</p>
	<%= f.text_field :postal_code, class: "postal_code" %>

	<p>住所</p>
	<%= f.text_field :address, class: "address" %>

	<p>電話番号</p>
	<%= f.text_field :phone_number, class: "phone_number" %>



<p><%= f.submit '保存' %></p>

<p><%= link_to "戻る", admins_users_path %></p>

<% end %>

app/views/admins/users/index.html.erb
<h1> ユーザー一覧</h1>

<%= search_form_for @search, url: admins_users_path  do |f| %>
  <div class="form-group">
    <%= f.label :name_kanji_cont, "Name" %>
    <%= f.text_field :name_kanji_cont, class: "form-control" %>
  </div>
  <div class="actions"><%= f.submit "Search" %></div>
<% end %>

<table>
 <thead>
    <tr>
      <th>ID</th>
      <th>ユーザー名</th>
      <th>メールアドレス</th>
    </tr>
  </thead>

<% if @result.any? %>
  <%= render @result %>
<% end %>

<% if @result.nil? %>
  <ul class="users">
    <%= render @users %>
  </ul>
<% end %>
</table>

<%= paginate @users %>

app/views/admins/users/show.html.erb
<div>
	<h2>マイページ</h2>

	<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %>
	<ul>
		<li><%= @user.name_kanji %></li>
		<li><%= @user.name_kana %></li>
		<li><%= @user.email %></li>
		<li><%= @user.postal_code %></li>
		<li><%= @user.address %></li>
		<li><%= @user.phone_number %></li>
	</ul>

<h2>購入履歴</h2>

<p><%= link_to "戻る", admins_users_path %></p>

</div>